(()=>{
 const esc=s=>String(s||'').replace(/\s+/g,' ').trim();
 const visible=el=>!!(el&&el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden'&&getComputedStyle(el).display!=='none');
 const cleanTitle=s=>esc(s||'').replace(/\s*[|–—-]\s*Football Talk.*$/i,'').trim();
 const pageTitle=()=>cleanTitle(document.querySelector('h1')?.textContent||document.title)||'Football Talk';
 function activeContent(){const selectors=['[aria-current="true"]','.active.match','.game.active','.fixture.active','.story.active','.article.active','.card.active','.panel.active','.stat-panel.active','article:target','section:target'];for(const sel of selectors){const el=[...document.querySelectorAll(sel)].find(visible);if(el)return el}const candidates=[...document.querySelectorAll('article,.story,.news-card,.article-card,.game,.fixture,.match-card,.card,.panel,.stat-panel,main section')].filter(visible);if(!candidates.length)return document.querySelector('main')||document.body;const y=Math.max(70,Math.min(innerHeight*.4,320));let best=null,bestScore=Infinity;for(const el of candidates){const r=el.getBoundingClientRect();if(r.bottom<60||r.top>innerHeight)continue;const contains=r.top<=y&&r.bottom>=y;const score=contains?Math.abs(r.top-y)*.1:Math.min(Math.abs(r.top-y),Math.abs(r.bottom-y))+100;if(score<bestScore){best=el;bestScore=score}}return best||candidates[0]}
 function contentInfo(){const root=activeContent(),heading=cleanTitle(root?.querySelector?.('h1,h2,h3,h4,.title,.headline,.teams')?.textContent)||pageTitle();let body='';const bits=[...root?.querySelectorAll?.('p,.summary,.description,.excerpt,.time,.score,.status')||[]].filter(visible).map(x=>esc(x.textContent)).filter(Boolean);if(bits.length)body=bits.slice(0,4).join(' — ');if(!body){const raw=esc(root?.innerText||'');body=raw.replace(heading,'').trim()}body=body.slice(0,420).replace(/\s+([,.;!?])/g,'$1');return{heading,body}}
 const payload=()=>{const c=contentInfo(),page=pageTitle();let text=c.heading;if(c.body&&c.body.toLowerCase()!==c.heading.toLowerCase())text+='\n'+c.body;text+='\n\nFootball Talk — where fans have their say.';return{title:'Football Talk — '+(c.heading||page),text,url:location.href}};
 async function share(){const p=payload();if(navigator.share){try{await navigator.share(p);return}catch(e){if(e?.name==='AbortError')return}}try{await navigator.clipboard.writeText(p.text+'\n'+p.url);toast('Content copied — ready to share')}catch(e){window.prompt('Copy and share:',p.text+'\n'+p.url)}}
 function toast(msg){const t=document.createElement('div');t.className='ft-share-toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
 function button(cls,label,html,fn){const b=document.createElement('button');b.type='button';b.className=cls;b.setAttribute('aria-label',label);b.innerHTML=html;b.addEventListener('click',fn);return b}
 function add(){if(document.querySelector('.ft-page-controls'))return;const bar=document.createElement('div');bar.className='ft-page-controls';bar.setAttribute('role','navigation');bar.setAttribute('aria-label','Page navigation and sharing');const inner=document.createElement('div');inner.className='ft-page-controls-inner';const back=button('ft-history-button','Go back','← <span>BACK</span>',()=>history.back()),forward=button('ft-history-button','Go forward','<span>FORWARD</span> →',()=>history.forward()),shareBtn=button('ft-share-button','Share the content you are viewing','<span aria-hidden="true">↗</span> SHARE',share);inner.append(back,forward,shareBtn);bar.appendChild(inner);document.body.prepend(bar);if(history.length<=1){back.disabled=true;back.setAttribute('aria-disabled','true')}if(matchMedia('(min-width:901px)').matches){const radio=document.querySelector('.home-radio-row');const install=document.querySelector('.ft-install-bar');bar.classList.add('ft-desktop-combined');if(radio){const radios=[...radio.querySelectorAll('.home-radio-bar')];radios.reverse().forEach(x=>inner.insertBefore(x,inner.firstChild));radio.remove()}if(install){const btn=install.querySelector('.ft-install-btn');if(btn){btn.textContent='JOIN FT →';btn.classList.add('ft-top-join');inner.insertBefore(btn,back)}install.remove()}}}
 const style=document.createElement('style');style.textContent=`.ft-page-controls{position:sticky;top:0;z-index:10000;width:100%;background:#0b0b0e;border-bottom:2px solid #f7c600;box-shadow:0 3px 10px rgba(0,0,0,.16)}@media(min-width:901px){.ft-page-controls.ft-desktop-combined{position:sticky;top:0;z-index:10000}.ft-desktop-combined .ft-page-controls-inner{gap:10px;padding:5px 18px;justify-content:flex-start}.ft-desktop-combined .home-radio-bar{width:auto!important;padding:6px 10px!important;border:0!important;background:transparent!important;flex:0 0 auto;font-size:12px}.ft-desktop-combined .home-radio-bar span{font-size:9px}.ft-desktop-combined .ft-install-icon{width:32px;height:32px;flex:0 0 32px;border-radius:8px;margin-left:10px}.ft-desktop-combined .ft-install-copy{flex:0 0 auto;min-width:0;max-width:330px}.ft-desktop-combined .ft-install-copy strong{font-size:13px}.ft-desktop-combined .ft-install-copy span{font-size:11px;margin-top:2px}.ft-desktop-combined .ft-install-btn{padding:8px 11px;font-size:10px;margin-left:auto}.ft-desktop-combined .ft-top-join{margin-left:auto}.ft-desktop-combined .ft-history-button,.ft-desktop-combined .ft-share-button{flex:0 0 auto}}.ft-page-controls-inner{width:100%;max-width:none;margin:0;padding:6px 18px;box-sizing:border-box;display:flex;align-items:center;justify-content:flex-end;gap:6px}.ft-page-controls button{appearance:none;border:1px solid #f7c600;border-radius:6px;min-height:34px;padding:7px 12px;font:900 10px/1 Inter,Arial,sans-serif;letter-spacing:.05em;cursor:pointer;white-space:nowrap}.ft-history-button{background:#fff;color:#111}.ft-share-button{background:#f7c600;color:#111}.ft-page-controls button:hover:not(:disabled){transform:translateY(-1px)}.ft-page-controls button:active:not(:disabled){transform:translateY(1px)}.ft-page-controls button:disabled{opacity:.35;cursor:default}.ft-share-toast{position:fixed;left:50%;top:52px;transform:translateX(-50%);z-index:10001;background:#111;color:#fff;border:2px solid #f7c600;border-radius:6px;padding:9px 14px;font:800 12px Inter,Arial,sans-serif;box-shadow:0 8px 24px rgba(0,0,0,.25)}@media(max-width:700px){.ft-page-controls-inner{max-width:1180px;margin:0 auto;justify-content:center;padding:4px 8px;gap:4px}.ft-page-controls button{min-height:30px;padding:6px 9px;font-size:9px;flex:1;max-width:112px}.ft-share-toast{top:46px;max-width:calc(100vw - 24px);text-align:center}}`;document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();