(()=>{
const css=`.ft-trending{background:#111;color:#fff;padding:18px 0;border-top:4px solid #f7c600;border-bottom:4px solid #f7c600}.ft-trending-inner{width:min(1180px,calc(100% - 28px));margin:auto}.ft-trending-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:12px}.ft-trending-kicker{margin:0;color:#f7c600;font-size:12px;font-weight:1000;letter-spacing:.12em}.ft-trending-title{margin:2px 0 0;font-size:clamp(22px,4vw,34px);font-weight:1000}.ft-trending-note{font-size:11px;color:#bbb}.ft-trending-list{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.ft-trend{display:flex;gap:9px;align-items:flex-start;background:#1d1d1d;border:1px solid #333;border-radius:12px;padding:11px;color:#fff;text-decoration:none;min-height:86px}.ft-trend:hover,.ft-trend:focus{border-color:#f7c600;outline:none}.ft-trend-num{color:#f7c600;font-size:22px;font-weight:1000;line-height:1}.ft-trend-copy{font-size:13px;font-weight:850;line-height:1.25}.ft-trend-tag{display:block;color:#aaa;font-size:9px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px}@media(max-width:900px){.ft-trending-list{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.ft-trending{padding:15px 0}.ft-trending-head{align-items:flex-start}.ft-trending-note{display:none}.ft-trending-list{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:5px}.ft-trend{min-width:78vw;scroll-snap-align:start}.ft-trending-list::-webkit-scrollbar{display:none}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
function clean(s){return String(s||'').replace(/\s+/g,' ').trim()}
function scoreCard(card,index){const title=clean(card.querySelector('h3')?.textContent);if(!title)return null;const type=clean(card.querySelector('.tag')?.textContent)||'Football';const button=card.querySelector('[data-story-index]');const storyIndex=button?.dataset.storyIndex;let points=100-index*7;if(/breaking|it's a go|its a go|full time/i.test(type))points+=25;if(/poll|debate/i.test(type))points+=10;return{title,type,storyIndex,points}}
function build(){if(document.getElementById('ft-trending'))return;const cards=[...document.querySelectorAll('#dynamic-posts .post-card,#debate-posts .post-card')];const items=cards.map(scoreCard).filter(Boolean).sort((a,b)=>b.points-a.points).slice(0,5);if(items.length<3)return;const sec=document.createElement('section');sec.id='ft-trending';sec.className='ft-trending';sec.innerHTML=`<div class="ft-trending-inner"><div class="ft-trending-head"><div><p class="ft-trending-kicker">🔥 WHAT FANS ARE READING</p><h2 class="ft-trending-title">Trending Now</h2></div><span class="ft-trending-note">Updated from Football Talk's latest stories & debates</span></div><div class="ft-trending-list">${items.map((x,i)=>`<a href="#latest" class="ft-trend" data-trending-story="${x.storyIndex??''}"><span class="ft-trend-num">${i+1}</span><span><span class="ft-trend-tag">${x.type.replace(/[<>&]/g,'')}</span><span class="ft-trend-copy">${x.title.replace(/[<>&]/g,'')}</span></span></a>`).join('')}</div></div>`;
const latest=document.getElementById('latest');latest?.parentNode.insertBefore(sec,latest);
sec.querySelectorAll('[data-trending-story]').forEach(a=>a.addEventListener('click',e=>{const n=a.dataset.trendingStory;if(n!==''&&typeof window.openArticle==='function'){e.preventDefault();window.openArticle(Number(n))}}));}
let tries=0;const timer=setInterval(()=>{tries++;build();if(document.getElementById('ft-trending')||tries>20)clearInterval(timer)},350);
})();