(()=>{
const REFRESH_MS=180000;
const MAX_ITEMS=3;
const css=`.ft-trending{background:#111;color:#fff;padding:18px 0;border-top:4px solid #f7c600;border-bottom:4px solid #f7c600}@media(min-width:901px){#ft-home-news-row{display:flex;align-items:stretch;width:100%;background:#0b0b0e}#ft-home-news-row>#ft-breaking-rotator{width:50%!important;margin:0!important;padding-right:7px!important;box-sizing:border-box}#ft-home-news-row>.ft-trending{width:50%;box-sizing:border-box;padding:18px 14px;border-top:0;border-bottom:1px solid #2a2a2e}#ft-home-news-row .ft-trending-inner{width:100%;margin:0}#ft-home-news-row .ft-trending-list{grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}#ft-home-news-row .ft-trending-head{align-items:flex-end}#ft-home-news-row .ft-trending-title{font-size:30px}#ft-home-news-row .ft-trend{min-height:205px;display:grid;grid-template-columns:auto 1fr;grid-template-rows:auto 1fr;align-content:start;overflow:hidden;padding:11px 11px 0}#ft-home-news-row .ft-trend-image{grid-column:1/-1;align-self:end;margin:12px -11px 0;display:block;height:105px;background:#151515;overflow:hidden}#ft-home-news-row .ft-trend-image img{width:100%;height:100%;display:block;object-fit:cover}#ft-home-news-row .ft-trend-fallback{display:flex;align-items:center;justify-content:center;gap:7px;background:linear-gradient(135deg,#171717,#0c0c0e);color:#f7c600}#ft-home-news-row .ft-trend-fallback b{font-size:24px}#ft-home-news-row .ft-trend-fallback small{font-size:9px;font-weight:1000;letter-spacing:.1em;color:#fff}}.ft-trending-inner{width:min(1180px,calc(100% - 28px));margin:auto}.ft-trending-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:12px}.ft-trending-kicker{margin:0;color:#f7c600;font-size:12px;font-weight:1000;letter-spacing:.12em}.ft-trending-title{margin:2px 0 0;font-size:clamp(22px,4vw,34px);font-weight:1000}.ft-trending-note{font-size:11px;color:#bbb}.ft-trending-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.ft-trend{display:flex;gap:9px;align-items:flex-start;background:#1d1d1d;border:1px solid #333;border-radius:12px;padding:11px;color:#fff;text-decoration:none;min-height:86px}.ft-trend:hover,.ft-trend:focus{border-color:#f7c600;outline:none}.ft-trend-num{color:#f7c600;font-size:22px;font-weight:1000;line-height:1}.ft-trend-copy{font-size:13px;font-weight:850;line-height:1.25}.ft-trend-tag{display:block;color:#aaa;font-size:9px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px}.ft-trend-image{display:none}@media(max-width:900px){.ft-trending-list{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.ft-trending{padding:15px 0}.ft-trending-head{align-items:flex-start}.ft-trending-note{display:none}.ft-trending-list{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:5px}.ft-trend{min-width:78vw;scroll-snap-align:start}.ft-trending-list::-webkit-scrollbar{display:none}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const esc=s=>clean(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const validUrl=s=>/^https:\/\//i.test(clean(s));
const timeValue=item=>{const raw=item?.publishedAt||item?.published_at||item?.published||item?.date||'';const t=Date.parse(raw);return Number.isFinite(t)?t:0};
const isLaunchStory=title=>{const s=clean(title).toLowerCase();return s.includes('welcome to football talk')||s.includes('football talk has a new home')};
const labelFor=item=>{const type=clean(item?.type).toUpperCase();const stage=clean(item?.stage).toUpperCase();if(type==='TRANSFER'){if(stage==='OFFICIAL')return'DEAL DONE';if(stage==='ITS_A_GO')return"IT'S A GO!";return'TRANSFER'}if(type.includes('BREAKING'))return'BREAKING NEWS';return type&&type!=='NEWS'?type:'NEWS'};
function normaliseNews(data){const raw=Array.isArray(data)?data:(data?.items||data?.news||[]);const seen=new Set();return raw.filter(item=>{const title=clean(item?.title);if(!title||isLaunchStory(title))return false;const key=title.toLowerCase();if(seen.has(key))return false;seen.add(key);return validUrl(item?.link||item?.url)}).sort((a,b)=>timeValue(b)-timeValue(a)||(Number(b?.relevance)||0)-(Number(a?.relevance)||0)).slice(0,MAX_ITEMS).map(item=>({title:clean(item.title),type:labelFor(item),href:clean(item.link||item.url),image:clean(item.image||item.image_url||''),published:timeValue(item)}));}
function domFallback(){return [...document.querySelectorAll('#dynamic-posts .post-card')].map(card=>{const title=clean(card.querySelector('h3')?.textContent);const type=clean(card.querySelector('.tag')?.textContent)||'NEWS';const href=card.querySelector('a[href^="https://"]')?.href||'';const img=card.querySelector('img');const raw=card.dataset.publishedAt||card.querySelector('.card-meta')?.textContent||'';return{title,type,href,image:img?.currentSrc||img?.src||'',published:Date.parse(raw)||0}}).filter(x=>x.title&&!isLaunchStory(x.title)&&validUrl(x.href)).sort((a,b)=>b.published-a.published).slice(0,MAX_ITEMS)};
function ensureSection(){let sec=document.getElementById('ft-trending');if(sec)return sec;sec=document.createElement('section');sec.id='ft-trending';sec.className='ft-trending';sec.innerHTML='<div class="ft-trending-inner"><div class="ft-trending-head"><div><p class="ft-trending-kicker">🔥 FOOTBALL TALK STORIES</p><h2 class="ft-trending-title">From the football conversation</h2></div><span class="ft-trending-note">Live stories · refreshes every 3 minutes</span></div><div class="ft-trending-list"></div></div>';if(window.matchMedia('(min-width:901px)').matches){const breaking=document.getElementById('ft-breaking-rotator');if(breaking){let row=document.getElementById('ft-home-news-row');if(!row){row=document.createElement('div');row.id='ft-home-news-row';breaking.parentNode.insertBefore(row,breaking);row.appendChild(breaking)}row.appendChild(sec)}else{const latest=document.getElementById('latest');latest?.parentNode.insertBefore(sec,latest)}}else{const latest=document.getElementById('latest');latest?.parentNode.insertBefore(sec,latest)}return sec}
function render(items){if(!items.length)return false;const sec=ensureSection();const list=sec.querySelector('.ft-trending-list');const signature=items.map(x=>x.title+'|'+x.href).join('||');if(list.dataset.signature===signature)return true;list.dataset.signature=signature;list.innerHTML=items.map((x,i)=>`<a href="${esc(x.href)}" class="ft-trend" target="_blank" rel="noopener noreferrer"><span class="ft-trend-num">${i+1}</span><span><span class="ft-trend-tag">${esc(x.type)}</span><span class="ft-trend-copy">${esc(x.title)}</span></span>${validUrl(x.image)?`<span class="ft-trend-image"><img src="${esc(x.image)}" alt="" loading="lazy" referrerpolicy="no-referrer"></span>`:`<span class="ft-trend-image ft-trend-fallback"><b>FT</b><small>FOOTBALL TALK</small></span>`}</a>`).join('');return true}
let loading=false;
async function refresh(){if(loading)return;loading=true;try{const response=await (window.ftFetchNews?window.ftFetchNews():fetch('/api/news?_='+Date.now(),{cache:'no-store'}));if(!response.ok)throw new Error('news unavailable');const items=normaliseNews(await response.json());if(!render(items))render(domFallback())}catch(_){render(domFallback())}finally{loading=false}}
function start(){refresh();setTimeout(refresh,1500);setInterval(refresh,REFRESH_MS);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('pageshow',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
