const BASES=['https://www.fotmob.com/api','https://www.fotmob.com/api/data'];
const HEADERS={accept:'application/json','user-agent':'Mozilla/5.0 (compatible; FootballTalk/1.0; +https://www.footballtalk.uk/)'};

export const FOTMOB_LEAGUES={
  premier:{id:47,name:'Premier League',country:'England',siteId:39},
  championship:{id:48,name:'EFL Championship',country:'England',siteId:40},
  faCup:{id:132,name:'FA Cup',country:'England',siteId:45},
  carabao:{id:133,name:'Carabao Cup',country:'England',siteId:48},
  championsLeague:{id:42,name:'UEFA Champions League',country:'Europe',siteId:2},
  europaLeague:{id:73,name:'UEFA Europa League',country:'Europe',siteId:3},
};
const KNOWN_BY_FOTMOB_ID=new Map(Object.values(FOTMOB_LEAGUES).map(x=>[x.id,x]));
function paramsString(params={}){const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&String(v)!=='')q.set(k,String(v));});const s=q.toString();return s?`?${s}`:'';}
async function fetchJson(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),9000);try{const response=await fetch(url,{headers:HEADERS,signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json();}finally{clearTimeout(timer);}}
export async function fotmobJson(route,params={}){const errors=[];for(const base of BASES){const url=`${base}/${route}${paramsString(params)}`;try{return await fetchJson(url);}catch(error){errors.push(`${url}: ${String(error.message||error)}`);}}throw new Error(`FotMob unavailable: ${errors.join(' | ')}`);}
export function fotmobDate(value){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value));const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${map.year}-${map.month}-${map.day}`;}
function teamLogo(id){return id?`https://images.fotmob.com/image_resources/logo/teamlogo/${id}.png`:'';}
function leagueLogo(id){return id?`https://images.fotmob.com/image_resources/logo/leaguelogo/${id}.png`:'';}
function numberOrNull(value){const n=Number(value);return value===null||value===undefined||value===''||!Number.isFinite(n)?null:n;}
function scoreFromString(match,side){const raw=match?.status?.scoreStr??match?.scoreStr??match?.status?.aggregateStr??match?.aggregateStr??'';const found=String(raw).match(/(-?\d+)\s*[-–:]\s*(-?\d+)/);if(!found)return null;return numberOrNull(side==='home'?found[1]:found[2]);}
function scoreValue(team,match,side){return numberOrNull(team?.score ?? team?.goals ?? team?.goalsFor ?? match?.status?.score?.[side] ?? match?.score?.[side] ?? match?.scores?.[side] ?? match?.[`${side}Score`]) ?? scoreFromString(match,side);}
export function fotmobStatus(match){const s=match?.status||{};const reason=String(s.reason?.short||s.reason?.long||s.reason||s.liveTime?.short||s.liveTime?.long||'');if(s.cancelled===true||/cancel/i.test(reason))return 'CANC';if(/postpon/i.test(reason))return 'PST';if(s.finished===true){if(/pen/i.test(reason))return 'PEN';if(/aet|extra time/i.test(reason))return 'AET';return 'FT';}if(s.started===true){if(/half.?time|\bht\b/i.test(reason))return 'HT';if(/pen/i.test(reason))return 'P';if(/extra/i.test(reason))return 'ET';return 'LIVE';}return 'NS';}
export function mapFotmobMatch(match,league={}){const home=match?.home||match?.homeTeam||{};const away=match?.away||match?.awayTeam||{};const date=match?.status?.utcTime||match?.utcTime||(match?.timeTS?new Date(Number(match.timeTS)).toISOString():null);const reason=String(match?.status?.liveTime?.short||match?.status?.reason?.short||match?.status?.reason||'');const minuteMatch=reason.match(/(\d{1,3})/);return{id:match?.id,date,timestamp:date?Math.floor(new Date(date).getTime()/1000):Math.floor(Number(match?.timeTS||0)/1000),status:fotmobStatus(match),elapsed:minuteMatch?Number(minuteMatch[1]):null,round:match?.round||match?.roundName||match?.tournamentStage||'',home:home?.name||home?.longName||'',away:away?.name||away?.longName||'',homeLogo:teamLogo(home?.id),awayLogo:teamLogo(away?.id),homeGoals:scoreValue(home,match,'home'),awayGoals:scoreValue(away,match,'away'),penaltyHome:numberOrNull(home?.penaltyScore??home?.penalties??match?.status?.penaltyScore?.home),penaltyAway:numberOrNull(away?.penaltyScore??away?.penalties??match?.status?.penaltyScore?.away),homeWinner:match?.status?.winner===home?.id||match?.winner===home?.id,awayWinner:match?.status?.winner===away?.id||match?.winner===away?.id,leagueId:league.siteId??league.id??match?.leagueId??match?.primaryId,leagueName:league.name||match?.leagueName||'',competition:league.name||match?.leagueName||'',source:'fotmob'};}
function allMatches(data){if(Array.isArray(data?.matches?.allMatches))return data.matches.allMatches;if(Array.isArray(data?.fixtures?.allMatches))return data.fixtures.allMatches;if(Array.isArray(data?.matches))return data.matches;if(Array.isArray(data?.fixtures))return data.fixtures;return[];}
export async function getFotmobLeagueMatches(league){const data=await fotmobJson('leagues',{id:league.id,ccode3:'GBR'});const details=data?.details||{};const resolved={...league,name:league.name||details.name,country:league.country||details.country};return allMatches(data).map(match=>mapFotmobMatch(match,resolved)).filter(f=>f.id&&f.date&&f.home&&f.away);}
export async function getFotmobMatchesByDate(dateKey){const compact=String(dateKey).replace(/-/g,'');const data=await fotmobJson('matches',{date:compact,timezone:'Europe/London',ccode3:'GBR'});return(data?.leagues||[]).map(group=>{const matchLeagueId=group?.matches?.find(m=>Number(m?.leagueId))?.leagueId;const rawId=Number(matchLeagueId||group?.id||group?.primaryId||0);const known=KNOWN_BY_FOTMOB_ID.get(rawId);const league={id:rawId,siteId:known?.siteId??rawId,name:known?.name||group?.name||'Other',country:known?.country||(group?.ccode==='ENG'?'England':group?.ccode||'International')};return{id:league.siteId,providerId:rawId,name:league.name,country:league.country,logo:leagueLogo(rawId),fixtures:(group?.matches||[]).map(match=>mapFotmobMatch(match,league)).filter(f=>f.id&&f.date&&f.home&&f.away).sort((a,b)=>(a.timestamp||0)-(b.timestamp||0))};}).filter(l=>l.fixtures.length);}
function findStandingsRows(data){if(Array.isArray(data?.table)){for(const part of data.table){const rows=part?.data?.table?.all||part?.table?.all||part?.data?.table;if(Array.isArray(rows)&&rows.length)return rows;}}if(Array.isArray(data?.table?.all))return data.table.all;if(Array.isArray(data?.standings))return data.standings;return[];}
export async function getFotmobStandings(league){const data=await fotmobJson('leagues',{id:league.id,ccode3:'GBR'});const rows=findStandingsRows(data);return{id:league.siteId,name:league.name,standings:rows.map((row,index)=>{const[gf,ga]=String(row?.scoresStr||'0-0').split('-').map(x=>Number(x)||0);const teamId=row?.id||row?.teamId||row?.team?.id;const played=Number(row?.played)||0;const win=Number(row?.wins??row?.win)||0;const draw=Number(row?.draws??row?.draw)||0;const lose=Number(row?.losses??row?.lose)||0;const rawPoints=numberOrNull(row?.pts??row?.points);const calculatedPoints=(win*3)+draw;const resultsAreComplete=(win+draw+lose)===played;const points=resultsAreComplete&&rawPoints!==calculatedPoints?calculatedPoints:(rawPoints??calculatedPoints);return{rank:Number(row?.idx||row?.rank)||index+1,team:row?.name||row?.team?.name||'',logo:teamLogo(teamId),played,win,draw,lose,goalsFor:Number(row?.scoresFor??row?.goalsFor)||gf,goalsAgainst:Number(row?.scoresAgainst??row?.goalsAgainst)||ga,goalsDiff:Number(row?.goalConDiff??row?.goalDiff??row?.goalsDiff)||(gf-ga),points,form:row?.form||'',description:row?.qualColor||row?.description||''};}).filter(r=>r.team)};}
export async function getFotmobMatchDetails(matchId){return fotmobJson('matchDetails',{matchId});}
export function withinRange(fixtures,fromMs,toMs){return(fixtures||[]).filter(f=>{const t=Number(f.timestamp||0)*1000;return t>=fromMs&&t<=toMs;});}
