const GRAPH_VERSION='v26.0';

function env(){return{pageId:process.env.FACEBOOK_PAGE_ID,token:process.env.FACEBOOK_PAGE_ACCESS_TOKEN};}
async function json(r){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||d?.message||`HTTP ${r.status}`);return d;}
async function pageCheck(pageId,token){const u=new URL(`https://graph.facebook.com/${GRAPH_VERSION}/${encodeURIComponent(pageId)}`);u.searchParams.set('fields','id,name');u.searchParams.set('access_token',token);const d=await json(await fetch(u,{cache:'no-store'}));return{id:d.id||null,name:d.name||null};}
async function start(pageId,token){const u=new URL(`https://graph.facebook.com/${GRAPH_VERSION}/${encodeURIComponent(pageId)}/video_reels`);u.searchParams.set('upload_phase','start');u.searchParams.set('access_token',token);return json(await fetch(u,{method:'POST',cache:'no-store'}));}
async function upload(uploadUrl,token,videoUrl){return json(await fetch(uploadUrl,{method:'POST',headers:{Authorization:`OAuth ${token}`,file_url:videoUrl},cache:'no-store'}));}
async function finish(pageId,token,videoId,description,title){const u=new URL(`https://graph.facebook.com/${GRAPH_VERSION}/${encodeURIComponent(pageId)}/video_reels`);u.searchParams.set('upload_phase','finish');u.searchParams.set('video_id',videoId);u.searchParams.set('video_state','PUBLISHED');if(description)u.searchParams.set('description',description);if(title)u.searchParams.set('title',title);u.searchParams.set('access_token',token);return json(await fetch(u,{method:'POST',cache:'no-store'}));}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method==='GET'&&String(req.query?.probeKey||'')){const key=String(req.query.probeKey).replace(/^\/+/, '');if(!/^videos\/[A-Za-z0-9._-]+\.mp4$/.test(key))return res.status(400).json({ok:false,error:'Invalid probe key'});const candidates=[`https://cdn.facelessreels.com/${key}`,`https://www.facelessreels.com/${key}`];const results=[];for(const url of candidates){try{const r=await fetch(url,{method:'GET',headers:{Range:'bytes=0-0','User-Agent':'Mozilla/5.0'},redirect:'follow',cache:'no-store'});results.push({url,status:r.status,contentType:r.headers.get('content-type'),contentLength:r.headers.get('content-length'),contentRange:r.headers.get('content-range'),finalUrl:r.url});}catch(e){results.push({url,error:String(e?.message||e)});}}return res.status(200).json({ok:true,key,results});}const {pageId,token}=env();if(!pageId||!token)return res.status(503).json({ok:false,configured:false,pageIdConfigured:Boolean(pageId),tokenConfigured:Boolean(token)});try{const page=await pageCheck(pageId,token);if(req.method==='GET'){let instagram=null;try{const iu=new URL(`https://graph.facebook.com/${GRAPH_VERSION}/${encodeURIComponent(pageId)}`);iu.searchParams.set('fields','instagram_business_account{id,username}');iu.searchParams.set('access_token',token);const idata=await json(await fetch(iu,{cache:'no-store'}));instagram=idata.instagram_business_account||null;}catch(e){instagram={error:String(e?.message||e)};}return res.status(200).json({ok:true,configured:true,mode:'facebook-reels-direct',page,instagram,publishing:{ready:true,requires:'POST with videoUrl and confirm=publish'}});}if(req.method!=='POST')return res.status(405).json({ok:false,error:'Method not allowed'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const videoUrl=String(body.videoUrl||'').trim();if(!videoUrl)return res.status(400).json({ok:false,error:'videoUrl is required'});if(body.confirm!=='publish')return res.status(400).json({ok:false,error:'confirm must equal publish; nothing was published'});const session=await start(pageId,token);if(!session.video_id||!session.upload_url)throw new Error('Meta did not return a Reel upload session');const uploaded=await upload(session.upload_url,token,videoUrl);if(uploaded.success!==true)throw new Error('Meta did not confirm Reel upload');const published=await finish(pageId,token,session.video_id,String(body.description||''),String(body.title||''));return res.status(200).json({ok:true,published:published.success===true,videoId:session.video_id,page});}catch(e){console.error('Facebook Reels publishing failed',e);return res.status(502).json({ok:false,error:String(e?.message||e)});}};
