const API_BASE='https://v3.football.api-sports.io';
const COMPETITIONS=[{id:39,name:'Premier League'},{id:40,name:'EFL Championship'},{id:48,name:'Carabao Cup'},{id:45,name:'FA Cup'}];
function londonDateString(date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const map=Object.fromEntries(parts.map(({type,value})=>[type,value]));return `${map.year}-${map.month}-${map.day}`}
function seasonFor(date){const year=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric'}).format(date));const month=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',month:'numeric'}).format(date));return month>=7?year:year-1}
function apiErrors(data){if(!data||!data.errors)return[];if(Array.isArray(data.errors))return data.errors.filter(Boolean).map(String);if(typeof data.errors==='object')return Object.entries(data.errors).map(([k,v])=>`${k}: ${v}`);return[String(data.errors)]}
async function readApi(url,key,label){const r=await fetch(url,{headers:{'x-apisports-key':key,accept:'application/json'}});const data=await r.json();const errors=apiErrors(data);if(!r.ok||errors.length)throw new Error(`${label}: ${errors.join('; ')||`HTTP ${r.status}`}`);return data.response||[]}
async function fixturesForCompetition(comp,key,date,season){const url=new URL(`${API_BASE}/fixtures`);url.searchParams.set('league',String(comp.id));url.searchParams.set('season',String(season));url.searchParams.set('date',date);url.searchParams.set('timezone','Europe/London');const rows=await readApi(url,key,comp.name);return rows.map(x=>({fixtureId:x.fixture?.id,date:x.fixture?.date,timestamp:x.fixture?.timestamp,status:x.fixture?.status?.short,elapsed:x.fixture?.status?.elapsed,leagueId:comp.id,leagueName:comp.name,home:x.teams?.home?.name,away:x.teams?.away?.name,homeLogo:x.teams?.home?.logo,awayLogo:x.teams?.away?.logo}))}
function mapPlayer(x){return {id:x.player?.id,name:x.player?.name,number:x.player?.number,pos:x.player?.pos,grid:x.player?.grid}}
async function lineupForFixture(fixture,key){const url=new URL(`${API_BASE}/fixtures/lineups`);url.searchParams.set('fixture',String(fixture.fixtureId));const rows=await readApi(url,key,`${fixture.home} v ${fixture.away}`);return rows.map(x=>({teamId:x.team?.id,team:x.team?.name,logo:x.team?.logo,formation:x.formation||'',coach:x.coach?.name||'',startXI:(x.startXI||[]).map(mapPlayer),substitutes:(x.substitutes||[]).map(mapPlayer)}))}
export default async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({error:'Method not allowed'})}const key=(process.env.API_FOOTBALL_KEY||'').trim();if(!key)return res.status(500).json({error:'API_FOOTBALL_KEY is not configured'});const now=new Date();const date=londonDateString(now);const season=seasonFor(now);try{const fixtureGroups=await Promise.all(COMPETITIONS.map(c=>fixturesForCompetition(c,key,date,season).catch(()=>[])));const fixtures=fixtureGroups.flat().sort((a,b)=>(a.timestamp||0)-(b.timestamp||0));const enriched=[];for(const fixture of fixtures){let lineups=[];try{lineups=await lineupForFixture(fixture,key)}catch(_){}enriched.push({...fixture,lineups})}res.setHeader('Cache-Control','public, s-maxage=180, stale-while-revalidate=120');return res.status(200).json({date,season,updatedAt:new Date().toISOString(),fixtures:enriched})}catch(error){res.setHeader('Cache-Control','no-store');return res.status(502).json({error:'Unable to load lineups right now',detail:error instanceof Error?error.message:String(error)})}}
