import {FOTMOB_LEAGUES,getFotmobLeagueMatches,getFotmobTeamMatches,getFotmobMatchDetails,getFotmobStandings} from '../lib/fotmob.js';

const API_BASE='https://v3.football.api-sports.io';
const FINISHED=new Set(['FT','AET','PEN']);
function apiErrors(data){if(!data||!data.errors)return[];if(Array.isArray(data.errors))return data.errors.filter(Boolean).map(String);if(typeof data.errors==='object')return Object.entries(data.errors).map(([k,v])=>`${k}: ${v}`);return[String(data.errors)];}
async function readApi(path,key,label){const r=await fetch(`${API_BASE}${path}`,{headers:{'x-apisports-key':key,accept:'application/json'}});let data;try{data=await r.json();}catch{throw new Error(`${label}: invalid response`);}const errors=apiErrors(data);if(!r.ok||errors.length)throw new Error(`${label}: ${errors.join('; ')||`HTTP ${r.status}`}`);return data.response||[];}
function seasonFor(date){const d=new Date(date);const y=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric'}).format(d));const m=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',month:'numeric'}).format(d));return m>=7?y:y-1;}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function resultLetter(f,teamId){const h=f.teams?.home?.id,a=f.teams?.away?.id,hg=f.goals?.home,ag=f.goals?.away;if(hg==null||ag==null)return null;if(hg===ag)return'D';return((h===teamId&&hg>ag)||(a===teamId&&ag>hg))?'W':'L';}
function mapRecent(rows,teamId){return rows.filter(x=>FINISHED.has(String(x.fixture?.status?.short||''))).slice(0,5).map(x=>({date:x.fixture?.date,home:x.teams?.home?.name||'',away:x.teams?.away?.name||'',homeGoals:x.goals?.home??null,awayGoals:x.goals?.away??null,result:resultLetter(x,teamId)}));}
function mapH2H(rows){return rows.filter(x=>FINISHED.has(String(x.fixture?.status?.short||''))).slice(0,5).map(x=>({date:x.fixture?.date,home:x.teams?.home?.name||'',away:x.teams?.away?.name||'',homeGoals:x.goals?.home??null,awayGoals:x.goals?.away??null}));}
function mapInjury(rows){return rows.slice(0,12).map(x=>({team:x.team?.name||'',player:x.player?.name||'',type:x.player?.type||'',reason:x.player?.reason||''})).filter(x=>x.player);}
function standingsContext(rows,homeId,awayId){const flat=(rows?.[0]?.league?.standings||[]).flat();const pick=id=>{const r=flat.find(x=>Number(x.team?.id)===Number(id));return r?{rank:r.rank??null,points:r.points??null,played:r.all?.played??null,form:r.form||'',goalDiff:r.goalsDiff??null}:null;};return{home:pick(homeId),away:pick(awayId)};}
function pickTeam(rows,name){const wanted=norm(name);return rows.map(x=>x.team||x).find(t=>norm(t?.name)===wanted)||rows.map(x=>x.team||x).find(t=>norm(t?.name).includes(wanted)||wanted.includes(norm(t?.name)))||null;}
function fotmobFixture(raw,id){const h=raw?.header||{},teams=h?.teams||[];const home=teams[0]||h?.homeTeam||{},away=teams[1]||h?.awayTeam||{},status=h?.status||{};return{id:Number(id),home:home?.name||'',away:away?.name||'',homeId:home?.id??null,awayId:away?.id??null,date:status?.utcTime||h?.status?.utcTime||null,status:status?.finished?'FT':status?.started?'LIVE':'NS',league:h?.leagueName||'Premier League'};}
function fotmobRecent(fixtures,team){const wanted=norm(team);return(fixtures||[]).filter(f=>FINISHED.has(String(f.status||''))&&(norm(f.home)===wanted||norm(f.away)===wanted)).sort((a,b)=>(b.timestamp||0)-(a.timestamp||0)).slice(0,5).map(f=>{const hg=f.homeGoals,ag=f.awayGoals,isHome=norm(f.home)===wanted;return{date:f.date,home:f.home,away:f.away,homeGoals:hg,awayGoals:ag,result:hg===ag?'D':((isHome&&hg>ag)||(!isHome&&ag>hg))?'W':'L'};});}
function flexibleMatch(o){if(!o||typeof o!=='object')return null;const teams=o.teams||[];const home=o.home||o.homeTeam||teams[0]||{},away=o.away||o.awayTeam||teams[1]||{};const hn=home.name||o.homeName||'',an=away.name||o.awayName||'';if(!hn||!an)return null;const score=o.status?.scoreStr||o.scoreStr||o.result||'';let hg=home.score??o.homeScore??o.goals?.home??null,ag=away.score??o.awayScore??o.goals?.away??null;if((hg==null||ag==null)&&score){const m=String(score).match(/(\d+)\s*[-–:]\s*(\d+)/);if(m){hg=Number(m[1]);ag=Number(m[2]);}}if(hg==null||ag==null)return null;return{date:o.status?.utcTime||o.utcTime||o.date||null,home:hn,away:an,homeGoals:Number(hg),awayGoals:Number(ag)};}
function findH2H(raw,home,away){const a=norm(home),b=norm(away),seen=new Set(),out=[];function walk(v,depth=0){if(depth>8||v==null)return;if(Array.isArray(v)){for(const x of v)walk(x,depth+1);return;}if(typeof v!=='object')return;const m=flexibleMatch(v);if(m){const h=norm(m.home),aw=norm(m.away);if((h===a&&aw===b)||(h===b&&aw===a)){const k=`${m.date}|${m.home}|${m.away}|${m.homeGoals}|${m.awayGoals}`;if(!seen.has(k)){seen.add(k);out.push(m);}}}for(const x of Object.values(v))walk(x,depth+1);}walk(raw);return out.filter(m=>new Date(m.date||0).getTime()<Date.now()-60000).sort((x,y)=>new Date(y.date||0)-new Date(x.date||0)).slice(0,5);}
function fotmobAvailability(raw,fixture){const out=[],seen=new Set(),home=fixture.home,away=fixture.away;const statusWords=/injur|suspend|doubt|knock|unavailable|illness|muscle|groin|knee|ankle|back|hamstring|cruciate|calf|foot/i,branchWords=/injur|suspend|unavail|doubt|missing/i;function teamFrom(v,hint){const t=v?.team?.name||v?.teamName||v?.club?.name||v?.clubName||hint||'';if(t&&(norm(t)===norm(home)||norm(t).includes(norm(home))||norm(home).includes(norm(t))))return home;if(t&&(norm(t)===norm(away)||norm(t).includes(norm(away))||norm(away).includes(norm(t))))return away;return hint||'';}function playerName(v){return v?.player?.name||v?.playerName||v?.name?.fullName||v?.name||v?.shortName||'';}function reasonOf(v){return v?.reason||v?.injury||v?.injuryType||v?.status?.reason||v?.status||v?.type||v?.description||v?.expectedReturn||'';}function walk(v,hint='',key='',depth=0,inBranch=false){if(depth>10||v==null)return;const branch=inBranch||branchWords.test(key);if(Array.isArray(v)){for(const x of v)walk(x,hint,key,depth+1,branch);return;}if(typeof v!=='object')return;let nextHint=teamFrom(v,hint);if(/home/i.test(key))nextHint=home;if(/away/i.test(key))nextHint=away;const blob=JSON.stringify(v);const player=playerName(v),reason=reasonOf(v);if((branch||statusWords.test(blob))&&player&&player!==home&&player!==away&&!/\svs?\s/i.test(player)&&player.length<70&&(branch||statusWords.test(`${reason} ${blob}`))){const team=teamFrom(v,nextHint);if(team){const all=`${key} ${reason} ${blob}`;const type=/suspend/i.test(all)?'Suspended':/doubt|question|knock/i.test(all)?'Doubt':'Injury';const cleanReason=typeof reason==='string'&&reason.length<120&&statusWords.test(reason)?reason:type;const k=`${norm(team)}|${norm(player)}`;if(!seen.has(k)){seen.add(k);out.push({team,player,type,reason:cleanReason||type});}}}for(const [k,x] of Object.entries(v))walk(x,nextHint,k,depth+1,branch);}walk(raw);return out.slice(0,16);}
async function fotmobFallback(id){const raw=await getFotmobMatchDetails(id),fixture=fotmobFixture(raw,id);let league=FOTMOB_LEAGUES.premier;if(!/premier league/i.test(fixture.league))league=FOTMOB_LEAGUES.championship;const [leagueFixtures,table]=await Promise.all([getFotmobLeagueMatches(league),getFotmobStandings(league)]);const pick=name=>table.standings.find(r=>norm(r.team)===norm(name));const ctx=r=>r?{rank:r.rank,points:r.points,played:r.played,form:r.form||'',goalDiff:r.goalsDiff}:null;return{fixture:{...fixture,leagueId:league.siteId,season:seasonFor(fixture.date||Date.now())},form:{home:fotmobRecent(leagueFixtures,fixture.home),away:fotmobRecent(leagueFixtures,fixture.away)},h2h:findH2H(raw,fixture.home,fixture.away),standings:{home:ctx(pick(fixture.home)),away:ctx(pick(fixture.away))},availability:fotmobAvailability(raw,fixture),availabilitySource:'FotMob match data',updatedAt:new Date().toISOString(),provider:'FotMob',fixtureIdProvider:'FotMob'};}

export default async function handler(req,res){
 if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({error:'Method not allowed'});}const id=String(req.query?.id||req.query?.fixture||'').trim();if(!/^\d+$/.test(id))return res.status(400).json({error:'A numeric fixture id is required'});const key=(process.env.API_FOOTBALL_KEY||'').trim();
 if(!key){try{const payload=await fotmobFallback(id);res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=600');return res.status(200).json(payload);}catch(error){console.error('FotMob pre-match fallback error:',String(error.message||error));return res.status(502).json({error:'Unable to load pre-match intelligence right now'});}}
 try{
  let fixtureRows=await readApi(`/fixtures?id=${encodeURIComponent(id)}&timezone=Europe%2FLondon`,key,'Fixture').catch(()=>[]),x=fixtureRows[0]||null,homeId,awayId,leagueId,season,fixtureMeta,providerIdType='API-Football';
  if(x){homeId=x.teams?.home?.id;awayId=x.teams?.away?.id;leagueId=x.league?.id;season=x.league?.season||seasonFor(x.fixture?.date||Date.now());fixtureMeta={id:Number(id),home:x.teams?.home?.name||'',away:x.teams?.away?.name||'',league:x.league?.name||'',date:x.fixture?.date,status:x.fixture?.status?.short||'NS'};}
  else{const raw=await getFotmobMatchDetails(id);fixtureMeta=fotmobFixture(raw,id);providerIdType='FotMob';season=seasonFor(fixtureMeta.date||Date.now());leagueId=/premier league/i.test(fixtureMeta.league)?39:null;const [homeTeams,awayTeams]=await Promise.all([readApi(`/teams?search=${encodeURIComponent(fixtureMeta.home)}`,key,'Home team lookup').catch(()=>[]),readApi(`/teams?search=${encodeURIComponent(fixtureMeta.away)}`,key,'Away team lookup').catch(()=>[])]);const homeTeam=pickTeam(homeTeams,fixtureMeta.home),awayTeam=pickTeam(awayTeams,fixtureMeta.away);homeId=homeTeam?.id||null;awayId=awayTeam?.id||null;if(!homeId||!awayId)throw new Error('Unable to resolve teams');}
  const formQuery=leagueId?`&league=${leagueId}&season=${season}`:'';
  const [homeRecent,awayRecent,h2h,standings,homeInjuries,awayInjuries]=await Promise.all([readApi(`/fixtures?team=${homeId}${formQuery}&last=8&timezone=Europe%2FLondon`,key,'Home form').catch(()=>[]),readApi(`/fixtures?team=${awayId}${formQuery}&last=8&timezone=Europe%2FLondon`,key,'Away form').catch(()=>[]),readApi(`/fixtures/headtohead?h2h=${homeId}-${awayId}&last=5&timezone=Europe%2FLondon`,key,'Head to head').catch(()=>[]),leagueId?readApi(`/standings?league=${leagueId}&season=${season}`,key,'Standings').catch(()=>[]):Promise.resolve([]),readApi(`/injuries?team=${homeId}&season=${season}${leagueId?`&league=${leagueId}`:''}`,key,'Home injuries').catch(()=>[]),readApi(`/injuries?team=${awayId}&season=${season}${leagueId?`&league=${leagueId}`:''}`,key,'Away injuries').catch(()=>[])]);
  res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=600');return res.status(200).json({fixture:{...fixtureMeta,homeId,awayId,leagueId,season},form:{home:mapRecent(homeRecent,homeId),away:mapRecent(awayRecent,awayId)},h2h:mapH2H(h2h),standings:standingsContext(standings,homeId,awayId),availability:mapInjury([...homeInjuries,...awayInjuries]),availabilitySource:'API-Football',updatedAt:new Date().toISOString(),provider:'API-Football',fixtureIdProvider:providerIdType});
 }catch(error){console.error('Pre-match intelligence error:',String(error.message||error));try{const payload=await fotmobFallback(id);res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=600');return res.status(200).json(payload);}catch{res.setHeader('Cache-Control','no-store');return res.status(502).json({error:'Unable to load pre-match intelligence right now'});}}
}
